#!/usr/bin/env bash
# Configures HAproxy load balancer on your lb-01 server.

sudo apt-get update
sudo apt-get install -y haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.default
echo "
listen load-balance
        bind :80
        bind :8080
        mode http
        balance roundrobin
        option httpchk HEAD / HTTP/1.1\r\nHost:\ localhost
        option forwardfor
        server 155759-web-01 18.210.15.86 check port 80
        server 155759-web-02 52.87.222.78 check port 80
" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null
sudo service haproxy restart